RUNIT TEST PROTOCOL -- Mon Dec  3 21:50:27 2012 
*********************************************** 
Number of test functions: 18 
Number of errors: 1 
Number of failures: 0 

 
1 Test Suite : 
GenABEL unit testing - 18 test functions, 1 error, 0 failures
ERROR in test.impute2databel: Error in .Call("iterator", tmp_fv@data, as.integer(0), as.integer(0),  : 
  "iterator" not resolved from current namespace (GenABEL)
